# Production Configuration

# Database
spring.datasource.url=${PS_DB_URL}
spring.datasource.username=${PS_DB_USERNAME}
spring.datasource.password=${PS_DB_PASSWORD}

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Logging
logging.level.root=WARN
logging.level.com.vicras.projectshield=INFO
